"use client";
import {useEffect,useState} from 'react';
import {api} from '@/lib/types';
export default function CreativeDirector({draftId,dirty,onApply}:{draftId:string|null;dirty:boolean;onApply:(result:any)=>void}){
 const [facts,setFacts]=useState(''),[audience,setAudience]=useState(''),[cta,setCta]=useState(''),[plan,setPlan]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;setPlan(null);setFacts('');setAudience('');setCta('');setError('');if(!draftId)return;let initial=true;
 const read=async()=>{try{const response=await api('ugc/'+draftId+'/plan');if(!active)return;setPlan(response.plan);if(initial&&response.plan?.brief){setFacts(response.plan.brief.facts);setAudience(response.plan.brief.audience);setCta(response.plan.brief.cta)}initial=false}catch(e){if(active)setError((e as Error).message)}};
 void read();const timer=setInterval(read,5000);return()=>{active=false;clearInterval(timer)}},[draftId]);
 const working=plan?.status==='queued'||plan?.status==='running';
 async function generate(){setBusy(true);setError('');try{await api('ugc/'+draftId+'/plan',{method:'POST',body:JSON.stringify({facts,audience,cta})});setPlan({status:'queued',updated:Date.now()})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="ugc-storyboard ugc-director"><div className="ugc-panel-title"><span>AI creative director</span><small>Local model · review before rendering</small></div><div className="ugc-storyboard-body"><p>Describe the product. AI proposes an advertising angle, hook, copy, layouts, motion and CTA. It reads these facts, not your photo. Verify every claim before applying the plan.</p><div className="ugc-scene-fields"><label>Verified product facts<textarea aria-label="Verified product facts" rows={4} maxLength={2000} value={facts} onChange={e=>setFacts(e.target.value)} placeholder="What it does, materials, real benefits and price if relevant. Do not include secrets."/></label><label>Target audience<input aria-label="Target audience" maxLength={300} value={audience} onChange={e=>setAudience(e.target.value)} placeholder="Who is this ad for?"/></label><label>Desired call to action<input aria-label="Desired call to action" maxLength={200} value={cta} onChange={e=>setCta(e.target.value)} placeholder="View product details / visit the store"/></label></div>{error&&<p role="alert" className="ugc-alert">{error}</p>}<button className="ugc-save" disabled={!draftId||dirty||busy||working||!facts.trim()||!audience.trim()||!cta.trim()} onClick={generate}>{busy||working?'Planning your ad…':plan?'Generate another concept':'Create AI ad concept'}</button><p className="ugc-help">{!draftId||dirty?'Save your draft before requesting a concept.':working?plan.status==='queued'?'Queued: keep Ollama and the Windows worker running. The model must be installed on your laptop.':'The local model is writing the plan. This can take several minutes.':'No external AI API. Your laptop must stay on. This creates a draft plan, not a rendered video or voiceover.'}</p>{plan?.status==='failed'&&<p role="alert" className="ugc-alert">{plan.error}</p>}{plan?.status==='complete'&&plan.result&&<div className="ugc-director-result"><span className="ugc-eyebrow">AI DRAFT · CHECK PRODUCT CLAIMS</span><h3>{plan.result.concept}</h3><p><strong>Hook:</strong> {plan.result.hook}</p><p><strong>CTA:</strong> {plan.result.cta}</p><div className="ugc-director-scenes">{plan.result.scenes.map((scene:any,i:number)=><article key={i}><small>{i+1} · {scene.layout} · {scene.seconds}s</small><strong>{scene.displayText}</strong><p>{scene.narration}</p>{scene.evidence&&<small>Fact to check: {scene.evidence}</small>}</article>)}</div><button className="ugc-save" onClick={()=>{if(!confirm('Apply this AI draft? This replaces the current script, scenes, palette, captions and music. Review product claims first.'))return;onApply(plan.result)}}>Apply reviewed plan to editor</button><p className="ugc-help">Background completion never changes your editor. Applying creates unsaved changes; save after reviewing.</p></div>}</div></section>;
}
