"use client";
import {useEffect,useState} from 'react';
import {Bookmark,Check,Plus,Trash2,RotateCcw} from 'lucide-react';
import {api,type ClipData} from '@/lib/types';
import {captionPresets} from '@/lib/editing.mjs';
import {templateSettings} from '@/lib/template-settings.mjs';
type Template={id:string;name:string;settings:Partial<ClipData>};
const fonts:Record<string,string>={sans:'Arial, sans-serif',serif:'Times New Roman, serif',mono:'Courier New, monospace',lato:'Loofy Lato, sans-serif',anton:'Loofy Anton, sans-serif'};
export function CaptionPresetPicker({data,onChange}:{data:ClipData;onChange:(value:Partial<ClipData>)=>void}){
 return <section className="preset-gallery"><div className="preset-section-title"><div><span className="eyebrow">STYLE YOUR STORY</span><h3>Caption looks</h3></div><span className="preset-count">12 looks</span></div><p className="preset-help">Pick a look, then fine-tune it below.</p><div className="caption-presets" aria-label="Caption presets">{captionPresets.map(preset=>{
 const {id,name,...settings}=preset;
 const selected=Object.entries(settings).every(([key,value])=>data[key as keyof ClipData]===value);
 return <button type="button" key={id} className={'caption-preset '+(selected?'selected':'')} aria-pressed={selected} onClick={()=>onChange(settings)}><div className="preset-sample" style={{fontFamily:fonts[preset.font],fontWeight:700,color:preset.color}}><span style={{background:preset.textEffect==='box'?preset.background:undefined,textShadow:['outline','shadow','highlight'].includes(preset.textEffect)?`1px 1px 0 ${preset.background},-1px -1px 0 ${preset.background}`:undefined}}>Make it <em style={{fontStyle:'normal',color:preset.textEffect==='highlight'?preset.highlightColor:undefined}}>memorable</em></span></div><div className="preset-caption"><strong>{name}</strong>{selected?<Check size={14}/>:<small>{preset.wordsPerCaption} words</small>}</div></button>;
 })}</div></section>;
}
export function TemplateLibrary({data,onChange}:{data:ClipData;onChange:(value:Partial<ClipData>)=>void}){
 const [templates,setTemplates]=useState<Template[]>([]),[name,setName]=useState(''),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[remove,setRemove]=useState<string|null>(null),[undo,setUndo]=useState<Partial<ClipData>|null>(null),[message,setMessage]=useState('');
 async function load(){try{const result=await api('templates');setTemplates(result.templates);setLoaded(true);setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load()},[]);
 async function save(){setBusy(true);setError('');try{await api(editing?'templates/'+editing:'templates',{method:editing?'PUT':'POST',body:JSON.stringify({name,settings:templateSettings(data)})});setName('');setEditing(null);await load();setMessage('Template saved to your account.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function deleteTemplate(id:string){setBusy(true);try{await api('templates/'+id,{method:'DELETE'});if(editing===id){setEditing(null);setName('');}setRemove(null);await load();setMessage('Template deleted.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="template-library"><summary><span><Bookmark size={16}/> My templates</span><span>{templates.length}/20</span></summary><div className="template-library-body"><p>Save caption style, frame, crop position and title visibility. Video text and cuts stay with each clip.</p><form onSubmit={e=>{e.preventDefault();void save()}}><label className="field">{editing?'Replace template with current settings':'Save this look'}<input value={name} onChange={e=>setName(e.target.value)} maxLength={50} required placeholder="e.g. My podcast style" aria-label="Template name"/></label><div className="inline"><button className="primary" disabled={busy||!loaded||!name.trim()}><Plus size={14}/>{editing?'Update template':'Save template'}</button>{editing&&<button className="text-button" type="button" onClick={()=>{setEditing(null);setName('')}}>Cancel</button>}</div></form>{error&&<p role="alert" className="error">{error} <button className="text-button" onClick={load}>Retry</button></p>}{!loaded&&!error&&<p role="status">Loading your templates…</p>}{loaded&&!templates.length&&<div className="template-empty">Your saved looks will appear here.</div>}{templates.map(template=><article className="saved-template" key={template.id}><div><strong>{template.name}</strong><small>{template.settings.ratio} · {template.settings.font} · {template.settings.textEffect}</small></div><div className="template-actions"><button className="subtle-button" disabled={busy} onClick={()=>{setUndo(templateSettings(data));onChange(template.settings);setMessage(`Applied ${template.name}. Clip text and timing are unchanged.`)}}>Apply</button><button className="text-button" disabled={busy} onClick={()=>{setEditing(template.id);setName(template.name)}}>Replace / rename</button><button className="icon-button" aria-label={`Delete template ${template.name}`} disabled={busy} onClick={()=>setRemove(template.id)}><Trash2 size={14}/></button></div>{remove===template.id&&<div className="template-delete">Delete this saved template?<button className="text-button" disabled={busy} onClick={()=>deleteTemplate(template.id)}>Delete</button><button className="text-button" onClick={()=>setRemove(null)}>Keep</button></div>}</article>)}{message&&<p role="status">{message}</p>}{undo&&<button className="text-button" onClick={()=>{onChange(undo);setUndo(null);setMessage('Previous settings restored.')}}><RotateCcw size={13}/> Undo template</button>}</div></details>;
}
