"use client";
import {useMemo,useState} from 'react';
import type {ClipData,Word} from '@/lib/types';
import {hookCandidates} from '@/lib/hooks.mjs';
type Hook={start:number;end:number;duration:number;text:string;signal:string;reason:string;context:string;contextEnd:number;review:string};
export function HookPicker({words,clip,onPreview,onApply,onUndo,onHeadline}:{words:Word[];clip:ClipData;onPreview:(hook:Hook)=>void;onApply:(hook:Hook)=>void;onUndo:(previous:Partial<ClipData>)=>void;onHeadline:(text:string)=>void}){
 const [focus,setFocus]=useState('all');
 const candidates=useMemo(()=>hookCandidates(words,clip,focus),[words,clip,focus]);
 const [previous,setPrevious]=useState<Partial<ClipData>|null>(null);
 return <section className="fundamentals clip-setting hook-picker" aria-label="Hook picker"><span className="eyebrow">OPEN WITH CURIOSITY</span><h3>Find your 1-3 second hook</h3><p>Choose an original spoken line, then let the explanation continue. These are transcript cues, not a promise of views.</p><label className="field">Opening angle<select aria-label="Opening angle" value={focus} onChange={e=>setFocus(e.target.value)}><option value="all">All angles</option><option value="question">Question / curiosity</option><option value="surprise">Unexpected contrast</option><option value="contrast">Mistake / warning</option><option value="curiosity">Information gap</option><option value="benefit">Useful outcome</option></select></label>{candidates.length?candidates.map((hook:Hook)=><article className="hook-option" key={hook.start}><small>{hook.signal} / {hook.duration.toFixed(1)}s / source {hook.start.toFixed(1)}s</small><blockquote>{hook.text}</blockquote><p>{hook.reason}</p><div className="hook-context"><small>WHAT FOLLOWS</small><p>{hook.context}</p></div><p className="hook-review">{hook.review}</p><div className="inline"><button className="subtle-button" onClick={()=>onPreview(hook)}>Preview hook</button><button className="subtle-button" onClick={()=>onPreview({...hook,end:hook.contextEnd})}>Hear the explanation</button><button className="subtle-button" disabled={Math.abs(clip.start-hook.start)<.02} onClick={()=>{setPrevious({start:clip.start,segments:clip.segments});onApply(hook)}}>Start clip here</button></div><small>Starting here removes the earlier part of this clip; the following explanation stays in order. Review the full clip for context.</small><button className="text-button" disabled={hook.text.length>80} onClick={()=>onHeadline(hook.text)}>Use quote as on-screen text (optional)</button></article>):<p>No strong 1-3 second cue found in this clip. Select another transcript passage or keep the current opening.</p>}{previous&&<button className="text-button" onClick={()=>{onUndo(previous);setPrevious(null)}}>Undo opening change</button>}</section>;
}
